spring:
  application:
    name: event-ticketing-api

  datasource:
    url: jdbc:postgresql://localhost:5432/event_ticketing
    username: postgres
    password: postgres123

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

server:
  port: 1010